import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "./(ladingpage)/components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" > 
      <head>
        <link rel="icon" href="/assets/images/favicon.ico" />
        <title>The Blog.</title>
      </head>
      <body className={inter.className}>
        <header className="fixed w-[100%] z-[100]">
          <NavigationBar />
        </header>
        {children}
      </body>
    </html>
  );
}
